version: '3'

services:
    dnsmasq:
        container_name: dnsmasq
        image: codesaru/dnsmasq:latest
        ports:
            - '53:53/tcp'
            - '53:53/udp'
            - '67:67/udp'
            - '67:67/tcp'
        dns:
            - 127.0.0.1
        cap_add:
            - NET_ADMIN

